apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-pod-httpd
spec:
  template:
    metadata:
      name: pod-httpd
      labels:
        app: pod-httpd
    spec:
      containers:
        - name: container-httpd
          image: httpd
          ports:
            - containerPort: 80
  replicas: 10
  selector:
    matchLabels:
      app: pod-httpd

---
apiVersion: v1
kind: Service
metadata:
  name: svc-pod-httpd
spec:
  type: NodePort
  selector:
    app: pod-httpd
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080