apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
spec:
  template:
    metadata:
      name: httpd
      labels:
        app: server-httpd
    spec:
      containers:
        - name: httpd
          image: httpd
          ports:
            - containerPort: 80
  replicas: 10
  selector:
    matchLabels:
      app: server-httpd