- hosts: all # fazer algo em todos os hosts
  become: true # se precirar use o sudo 
  tasks: # aqui começa lista de tarefas 
  - name: alterando nome dos hosts 
    hostname:
      name: '{{ new_hostname }}'

- hosts: banana # começa outra sequencia de tarefas 
  become: true 
  tasks:
  - name: adicionar chave GPG do docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: adicionar repositório do instalador do docker
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: instalar o docker # mesma que fazer sudo apt-get install docker-ce docker-ce-cle containerd.io
    apt:
      name: "{{item}}"
      state: latest
      update_cache: yes
    loop:
      - docker-ce
      - docker-ce-cli
      - containerd.io
        
  - name: criando diretório de config do Docker
    file: path=/etc/docker state=directory

  - name: trocando driver do Docker para systemd
    copy:
      dest: "/etc/docker/daemon.json"
      content: |
        {
        "exec-opts": ["native.cgroupdriver=systemd"]
        }

  - name: adicionar $USER no grupo Docker
    ansible.builtin.user:
      name: ubuntu
      group: docker

#  - name: adicionar user via shell
#    shell: "sudo usermod -aG docker ubuntu"
